### PR TITLE
Ridwan-factoids

### PR DESCRIPTION
**Pull request by lunadine**
Dear Nathan,

I hope I am doing this correctly now, I published my branch and uploaded my changes (as I think) in this new branch and I send you a pull request now, please let me know if something went wrong.

all the best

### CODE REVIEW

**Comment by lunadine** [comment]
Ah I see something went wrong with my changes, one moment

**Comment by lunadine** [comment]
okay there should be an updated version of lhom-ar-14 now with my factoids, but it appears as if it is not highlighting my changes

**Comment by nathangibson** [comment]
Okay the problem is that the lhom-ar-14.xml file you uploaded is not in the same folder as the original one. It should be in usaybia-data/data/texts/tei/lhom/ (https://github.com/usaybia/usaybia-data/tree/branch.nadine/data/texts/tei/lhom). 

But let me suggest this -- I need to move the lhom texts and reorganize the whole repository anyway. I'm going to delete most things and put them in an "archive" branch. So I'll do that first and then we can correct this, since the location will be different then.

**Comment by nathangibson** [comment]
OK I'm updating your branch from the cleaned-up master branch using the merge function ...

**Comment by nathangibson** [comment]
@lunadine Your branch is up-to-date now and your file with the factoids is now at  usaybia-data/data/texts/tei/lhom-ar-14.xml on your branch (https://github.com/usaybia/usaybia-data/blob/branch.nadine/data/texts/tei/lhom-ar-14.xml). I will comment/suggest changes there. 

Let's not merge it into the master branch yet until we settle some of the questions you've raised. Therefore closing this pull request and you can do another pull request when we're ready.

**Comment by lunadine** [comment]
@nathangibson ,
perfect thanks so much for this and for your feedback on my questions! maybe it is best I share my screen with you on our next meeting and show you specifically the problem I encountered from time to time when tagging

**Pull request closed without merging**
